# Generated by Django 4.0.3 on 2022-08-26 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.IntegerField(verbose_name='Employee ID')),
                ('emp_name', models.CharField(max_length=500, verbose_name='Name')),
                ('emp_position', models.CharField(max_length=500, verbose_name='Position')),
                ('emp_dayoff', models.CharField(max_length=100, verbose_name='Dayoff')),
                ('emp_shift', models.CharField(max_length=100, verbose_name='Shift')),
                ('emp_remarks', models.TextField(blank=True, null=True, verbose_name='Remarks')),
            ],
        ),
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=500, verbose_name='Group Name')),
                ('group_desc', models.TextField(verbose_name='Description')),
                ('filter_string', models.TextField(verbose_name='Filter Text')),
                ('group_sort', models.IntegerField(verbose_name='Group Sort')),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mod_name', models.CharField(max_length=200, verbose_name='Module Name')),
                ('mod_url', models.CharField(max_length=200, verbose_name='Module URL')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order_code', models.CharField(blank=True, editable=False, max_length=100, null=True, verbose_name='Order Code')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('req_code', models.CharField(blank=True, editable=False, max_length=100, null=True, verbose_name='Request Code')),
                ('req_asset', models.CharField(max_length=300, verbose_name='Asset')),
                ('req_date', models.DateField(verbose_name='Date')),
                ('req_status', models.CharField(max_length=300, verbose_name='Status')),
                ('req_type', models.CharField(max_length=300, verbose_name='Type')),
                ('req_reptype', models.CharField(max_length=300, verbose_name='Repair Type')),
                ('req_workshop', models.CharField(max_length=300, verbose_name='Workshop')),
                ('req_description', models.TextField(verbose_name='Description')),
                ('req_update', models.BooleanField(verbose_name='Update')),
            ],
        ),
        migrations.CreateModel(
            name='Selection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sel_name', models.CharField(max_length=300, verbose_name='Selection Name')),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp_name', models.CharField(max_length=500, verbose_name='Template Name')),
                ('temp_default', models.BooleanField(default='False', verbose_name='Set Default')),
                ('temp_filter', models.ManyToManyField(blank=True, to='ams.filter', verbose_name='Filter')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sec_name', models.CharField(max_length=200, verbose_name='Section Name')),
                ('sec_icon', models.CharField(max_length=200, verbose_name='Selection Icon')),
                ('sec_mod', models.ManyToManyField(blank=True, to='ams.module', verbose_name='Selection Modules')),
            ],
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('param_name', models.CharField(max_length=200, verbose_name='Parameter Name')),
                ('param_sel', models.ManyToManyField(blank=True, to='ams.selection', verbose_name='Parameter Selections')),
            ],
        ),
        migrations.AddField(
            model_name='module',
            name='mod_param',
            field=models.ManyToManyField(blank=True, to='ams.parameter', verbose_name='Module Parameters'),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attend_date', models.CharField(max_length=100, verbose_name='Attendance Date')),
                ('attend_timein', models.CharField(max_length=100, verbose_name='Time In')),
                ('attend_timeout', models.CharField(max_length=100, verbose_name='Time Out')),
                ('attend_status', models.CharField(max_length=500, verbose_name='Attendance Status')),
                ('attend_shiftfrom', models.CharField(max_length=100, verbose_name='Shift From')),
                ('attend_shiftto', models.CharField(max_length=100, verbose_name='Shift To')),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ams.employee', verbose_name='Employee ID')),
            ],
        ),
    ]
