# Generated by Django 4.0.3 on 2022-09-13 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.IntegerField(verbose_name='Employee ID')),
                ('emp_name', models.CharField(max_length=500, verbose_name='Name')),
                ('emp_position', models.CharField(max_length=500, verbose_name='Position')),
                ('emp_salary', models.PositiveIntegerField(verbose_name='Basic Salary')),
                ('emp_dayoff', models.CharField(max_length=100, verbose_name='Dayoff')),
                ('emp_shift', models.CharField(max_length=100, verbose_name='Shift')),
                ('emp_remarks', models.CharField(blank=True, max_length=500, null=True, verbose_name='Remarks')),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mod_name', models.CharField(max_length=200, verbose_name='Module Name')),
                ('mod_url', models.CharField(max_length=200, verbose_name='URL')),
            ],
        ),
        migrations.CreateModel(
            name='Selection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sel_name', models.CharField(max_length=300, verbose_name='Selection Name')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sec_name', models.CharField(max_length=200, verbose_name='Section Name')),
                ('sec_icon', models.CharField(max_length=200, verbose_name='Icon')),
                ('sec_mod', models.ManyToManyField(blank=True, to='ams.module', verbose_name='Modules')),
            ],
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('param_name', models.CharField(max_length=200, verbose_name='Parameter Name')),
                ('param_sel', models.ManyToManyField(blank=True, to='ams.selection', verbose_name='Selections')),
            ],
        ),
        migrations.AddField(
            model_name='module',
            name='mod_param',
            field=models.ManyToManyField(blank=True, to='ams.parameter', verbose_name='Parameters'),
        ),
    ]
