# Generated by Django 4.0.3 on 2022-09-13 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(max_length=10, verbose_name='Asset ID')),
                ('asset_model', models.CharField(max_length=50, verbose_name='Model')),
                ('asset_type', models.CharField(max_length=100, verbose_name='Type')),
                ('asset_sector', models.CharField(max_length=50, verbose_name='Sector')),
                ('asset_area', models.CharField(max_length=50, verbose_name='Area')),
                ('asset_serial', models.CharField(max_length=300, verbose_name='Serial')),
                ('asset_desc', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
        ),
    ]
