# Generated by Django 4.0.3 on 2022-09-27 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0002_asset'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.IntegerField(verbose_name='Employee ID')),
                ('attend_date', models.CharField(max_length=100, verbose_name='Attendance Date')),
                ('attend_timein', models.CharField(max_length=50, verbose_name='Time In')),
                ('attend_timeout', models.CharField(max_length=50, verbose_name='Time Out')),
                ('attend_status', models.CharField(max_length=300, verbose_name='Attendance Status')),
            ],
        ),
    ]
