# Generated by Django 4.0.3 on 2022-09-27 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0003_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='attend_remarks',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Remarks'),
        ),
    ]
