# Generated by Django 4.0.3 on 2022-10-05 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0005_request_alter_asset_asset_area_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='req_code',
        ),
        migrations.RemoveField(
            model_name='request',
            name='req_completeat',
        ),
        migrations.RemoveField(
            model_name='request',
            name='req_createshop',
        ),
        migrations.RemoveField(
            model_name='request',
            name='req_startat',
        ),
        migrations.RemoveField(
            model_name='request',
            name='req_type',
        ),
        migrations.AddField(
            model_name='request',
            name='req_enghr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Emgine Hour'),
        ),
        migrations.AddField(
            model_name='request',
            name='req_fuel',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Fuel Quantity'),
        ),
        migrations.AddField(
            model_name='request',
            name='req_id',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Request ID'),
        ),
        migrations.AddField(
            model_name='request',
            name='req_km',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Kilometer'),
        ),
        migrations.AddField(
            model_name='request',
            name='req_maint',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Maintenance Type'),
        ),
        migrations.AddField(
            model_name='request',
            name='req_repair',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Repair Type'),
        ),
        migrations.AlterField(
            model_name='request',
            name='req_date',
            field=models.CharField(max_length=100, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='request',
            name='req_physloc',
            field=models.CharField(max_length=500, verbose_name='Physical Location'),
        ),
        migrations.AlterField(
            model_name='request',
            name='req_status',
            field=models.CharField(max_length=300, verbose_name='Status'),
        ),
    ]
