# Generated by Django 4.0.3 on 2022-10-05 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0006_remove_request_req_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='req_asset',
            new_name='object_id',
        ),
        migrations.AlterField(
            model_name='request',
            name='req_status',
            field=models.CharField(max_length=300, verbose_name='Request Status'),
        ),
    ]
