# Generated by Django 4.0.3 on 2022-10-23 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0007_rename_req_asset_request_object_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='req_enghr',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Engine Hour'),
        ),
        migrations.AlterField(
            model_name='request',
            name='req_fuel',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Fuel Quantity'),
        ),
        migrations.AlterField(
            model_name='request',
            name='req_km',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Kilometer'),
        ),
    ]
