# Generated by Django 4.0.3 on 2022-10-23 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0008_alter_request_req_enghr_alter_request_req_fuel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='req_enghr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Engine Hour'),
        ),
        migrations.AlterField(
            model_name='request',
            name='req_fuel',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Fuel Quantity'),
        ),
        migrations.AlterField(
            model_name='request',
            name='req_km',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Kilometer'),
        ),
    ]
